[versions]
datafaker = "2.5.4"
flyway = "12.0.1"
hikaricp = "7.0.2"
jackson-datatype-jsr = "2.21.0"
kafka = "4.1.1"
koin = "4.1.1"
kotest-extensions = "2.0.0"
kotest = "6.1.3"
kotlin-version = "2.3.0"
ktor-version = "3.4.0"
logback-version = "1.5.29"
micrometer-prometheus = "1.16.3"
mockk = "1.14.9"
postgresql = "42.7.10"
testcontainers = "2.0.3"
testcontainers-postgres = "1.21.4"
logstashEncoder = "9.0"
coroutines-test = "1.10.2"
swagger = "3.4.0"
ktlint = "14.0.1"
valkey-version = "5.5.0"

[libraries]
database-flyway-core = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
database-hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
database-postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
datafaker = { module = "net.datafaker:datafaker", version.ref = "datafaker" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson-datatype-jsr" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-logger = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-ktor = { module = "io.kotest.extensions:kotest-assertions-ktor", version.ref = "kotest-extensions" }
kotest-junit = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor-version" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor-version" }
ktor-server-swagger = { module = "io.ktor:ktor-server-swagger", version.ref = "swagger" }
ktor-server-openapi = { module = "io.ktor:ktor-server-openapi", version.ref = "swagger" }
ktor-server-micrometer = { module = "io.ktor:ktor-server-metrics-micrometer", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor-version" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-version" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-version" }
ktor-client-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor-version" }
ktor-client-apache5 = { module = "io.ktor:ktor-client-apache5", version.ref = "ktor-version" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor-version" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor-version" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor-version" }
ktor-server-callid = { module = "io.ktor:ktor-server-call-id", version.ref = "ktor-version" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor-version" }
ktor-server-statuspages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor-version" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor-version" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
micrometer-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer-prometheus" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-postgres = { module = "org.testcontainers:postgresql", version.ref = "testcontainers-postgres" }
logstash = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstashEncoder" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-test" }
valkey-java = { module = "io.valkey:valkey-java", version.ref = "valkey-version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor-version" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }

[bundles]
kotest = ["kotest-assertions-core", "kotest-junit", "kotest-property", "kotest-assertions-ktor"]
database = ["database-flyway-core", "database-hikaricp", "database-postgresql"]
testcontainers = ["testcontainers", "testcontainers-postgres"]
ktor-client = ["ktor-client-core", "ktor-client-content-negotiation", "ktor-client-jackson", "ktor-client-apache5"]
ktor-server = ["ktor-server-core", "ktor-server-config-yaml", "ktor-server-swagger", "ktor-server-openapi", "ktor-server-micrometer", "ktor-server-netty", "ktor-server-auth", "ktor-server-auth-jwt", "ktor-server-callid", "ktor-server-content-negotiation", "ktor-server-statuspages"]
